mainprefix: "#"
defaultjoinmessage: "**{user} Joined Invited By {Inviter} (Invites: {inv})**"
defaultleavemessage: "**{user} Left, Invited by {inviter}**"
token: "NzYyMDM5NTg4MjUyMDI0ODQy.X3jWqw.6YKeBEntwP_ngbhKfJdah7JS-mA"
color: "BLUE"
